---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: create attachment
      file:
        path: /tmp/SNOW_test
        state: touch
        mode: '0755'
    - name: add content
      shell: echo 'SNOW test' >/tmp/SNOW_test
    - name: Update the existing incident to add attachments
      snow_record:
        username: "Fu.Hua.Xu@kyndryl.com"
        password: "MyPassword"
        instance: "aiaprod"
        state: present
        number: "INC3259413"
        attachment: "/tmp/SNOW_test"
